### ISSUE TITLE
Authentication - VB.net

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#101]
Please add in:
1. Code samples found in the appropriate `/source/code/{language}/authentication` directory.
2. Any necessary text to the `auth_n.rst` file. Areas that don't have code samples have been marked with `(todo)`. 

All work should be done in this branch: https://github.com/stormpath/stormpath-documentation/tree/the_one_prod_guide

**Comment by nbarbettini** [comment]
Closed via #126

**Comment by jakubvul** [comment]
Needs one more code example: `create_account_linkedin_providerdata_auth_code.vb`
