### ISSUE TITLE
Authentication - C#

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#106]
Please add in:
1. Code samples found in the appropriate `/source/code/{language}/authentication` directory.
2. Any necessary text to the `auth_n.rst` file. Areas that don't have code samples but still need your attention have been marked with `(todo)`. 

All work should be done in this branch: https://github.com/stormpath/stormpath-documentation/tree/the_one_prod_guide

**Comment by nbarbettini** [comment]
Closed via #126

**Comment by jakubvul** [comment]
Hey Nate, I added a code example we missed: `create_account_linkedin_providerdata_auth_code.cs`
