### ISSUE TITLE
Data Model Diagram

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#112]
It would be useful to have a diagram of all the Stormpath resources and how they interrelate.

**Comment by jakubvul** [comment]
![stormpath_erd 2](https://cloud.githubusercontent.com/assets/4551905/15080361/a540ff70-138b-11e6-9db2-8754a6f55c16.png)

**Comment by jakubvul** [comment]
Any comments @omgitstom @lhazlewood ?

**Comment by omgitstom** [comment]
I think this is good enough from an understanding point of view.  It might be important to outline that an account store mapping can also be a group.

On top of that, I ask that where ever this goes gets some information and a link for multi-tenant data models

**Comment by omgitstom** [comment]
misclicked

**Comment by mokellymo** [comment]
@jakubswiatczak are you planning on representing Organizations?

**Comment by jakubvul** [comment]
@mokellymo You'll find those represented here: https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html#tenants-as-directories-example

And here: https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html#strategy-2-tenants-as-groups

**Comment by omgitstom** [comment]
@mokellymo my comment above answers that question.  I think it might make sense to have a reference to multi-tenancy guide separately.

**Comment by mokellymo** [comment]
Thanks!
