### ISSUE TITLE
LinkedIn can authenticate using authorization code

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-documentation#116]
https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#linkedin

I was just testing this today: we can actually use authorization code to authenticate for LinkedIn, just like Google. (The docs say that the developer has to take an additional step to exchange their auth code for an access token, but that's incorrect)

**Comment by jakubvul** [comment]
This actually just looks like it was an incomplete edit, since we don't specify how you would exchange an Auth Code for an Access Token. I've removed all mention of a code:

```
Step 3: Access an Account with LinkedIn Tokens
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

To access or create an Account in your new LinkedIn Directory, you must gather a LinkedIn **Access Token** on behalf of the user. This requires leveraging `LinkedIn's OAuth 2.0 protocol <https://developer.linkedin.com/docs/oauth2>`_ and the user’s consent for your application’s permissions.

Generally, this will include embedding a link in your site that will send an authentication request to LinkedIn. Once the user has authenticated, LinkedIn will redirect the response to your application, along with an Access Token. This is documented in detail in LinkedIn's `Authenticating with OAuth 2.0 page <https://developer.linkedin.com/docs/oauth2#hero-par_longformtext_3_longform-text-content-par_resourceparagraph_3>`_.

.. note::

    It is required that your LinkedIn application requests the ``r_basicprofile`` and ``r_emailaddress`` scopes from LinkedIn. If the access token does not grant these scopes, you will not be able to get an Account with an access token. For more information about LinkedIn scopes, see `LinkedIn's "Profile Fields" documentation <https://developer.linkedin.com/docs/fields>`_.

Once the Access Token is gathered, you can send an HTTP POST:

.. code-block:: http

  POST /v1/applications/YOUR_APP_ID/accounts HTTP/1.1
  Host: api.stormpath.com
  Content-Type: application/json;charset=UTF-8

  {
    "providerData": {
      "providerId": "linkedin",
      "accessToken": "TOKEN_FROM_LINKEDIN"
    }
  }

Stormpath will use the ``accessToken`` provided to retrieve information about your LinkedIn Account, then return a Stormpath Account. The HTTP Status code will tell you if the Account was created (HTTP 201) or if it already existed in Stormpath (HTTP 200).
```

**Comment by edjiang** [comment]
Jakub,

[LinkedIn OAuth](https://developer.linkedin.com/docs/oauth2) works in the following way:
1. The application redirects the user to LinkedIn, which prompts them to authorize the application.
2. LinkedIn redirects the user back to the application, with an authorization code. 
3. The application must make a POST request to LinkedIn to exchange the auth code for an access token. 
4. The application can now use the access token to make requests to the LinkedIn API and query for information about the user.

In my testing yesterday against the Stormpath REST API, the REST API supports taking the authorization code from step 2. This delivers more customer convenience. 

So the flow could be:
1. The application redirects the user to LinkedIn, which prompts them to authorize the application.
2. LinkedIn redirects the user back to the application, with an authorization code. 
3. The application sends this to Stormpath, and retrieves the user account. 
4. Viola!

OR:
1. The application redirects the user to LinkedIn, which prompts them to authorize the application.
2. LinkedIn redirects the user back to the application, with an authorization code. 
3. The application must make a POST request to LinkedIn to exchange the auth code for an access token. 
4. The application sends this to Stormpath, and retrieves the user account. 
5. Viola!

The second flow takes more work on the developer side, but might be used if they want to also retrieve user data from LinkedIn for whatever purposes. But we support both, and should document both (just like how we do for Google login)

**Comment by edjiang** [comment]
Facebook, for reference, uses the implicit grant type (not authorization code grant type) by default, so you only get an access token. That's why we only mention access token for Facebook (and only support access token). But LinkedIn doesn't support implicit. 

Take a look at my handy dandy chart of what we support here:

https://github.com/stormpath/stormpath-framework-spec/pull/104

**Comment by mdeggies** [comment]
On that note, is there a universal endpoint for all of our integrations (ie: /callbacks/linkedin, /callbacks/facebook, /callbacks/google)?

**Comment by edjiang** [comment]
Yep! https://github.com/stormpath/stormpath-framework-spec/blob/master/social.md
