### ISSUE TITLE
Note Required Fields for Agents

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-documentation#118]
https://docs.stormpath.com/rest/product-guide/latest/reference.html#ldap-agent
- The `config` property is required when creating an agent.
- The `config.accountConfig` property is also required.
- The `config.groupConfig` property is also required.
- `config.referralMode` is listed in the docs, but isn't valid according to the REST API responses I'm getting. Ping @omgitstom ?
- `config.ignoreReferralIssues` is also listed in the docs but not valid according to the REST API.
- `config.status` fields are listed as having values 'online', 'offline', and 'error'. But I believe they are returned in uppercase, eg: 'ONLINE', 'OFFLINE', 'ERROR'.

**Comment by jakubvul** [comment]
- `config.referralMode` and `config.ignoreReferralIssues` are only included for AD Agents, not LDAP Agents. 
- `status` should definitely be all-caps.

**Comment by jakubvul** [comment]
I've also gone through and indicated which attributes are optional, or AD-only VS non-AD only. I feel like this is a better strategy than highlighting which ones are required, since almost everything is required.

**Comment by jakubvul** [comment]
I've also added a small diagram to both the Authentication and Reference chapters to show all the objects that you need to send in order to create an LDAP Directory:

```
  directory
    └──provider
        └──agent
            └──config
                ├──accountConfig
                └──groupConfig
```
