### ISSUE TITLE
Incorrect Organization Account Store Mapping Docs

### ISSUE THREAD

**Issue by rdegges** [stormpath/stormpath-documentation#119]
https://docs.stormpath.com/rest/product-guide/latest/reference.html#create-an-organization-account-store-mapping
- The `organization` link is REQUIRED to create an OrganizationAccountStoreMapping, but we do not say so in the creation docs.
- The `application` field is listed as required to create an OrganizationAccountStoreMapping, but it is not. We should remove it.

**Comment by jakubvul** [comment]
Or, to put it differently, it says `application` where it should say `organization`.
