### ISSUE TITLE
ID Site OAuth Access Token Grant Type

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#12]
https://stormpath.atlassian.net/wiki/display/AM/ID+Site+OAuth+Access+Token+Grant+Type

**Comment by jakubvul** [comment]
Added "Exchanging the ID Site JWT for an OAuth Token" section to ID Site chapter.

**Comment by jakubvul** [comment]
https://docs.stormpath.com/rest/product-guide/latest/008_idsite.html#exchanging-the-id-site-jwt-for-an-oauth-token
