### ISSUE TITLE
Inaccurate documentation for REST

### ISSUE THREAD

**Issue by artburkart** [stormpath/stormpath-documentation#127]
I can't find where the code lives, otherwise I'd provide a link, but I noticed the documentation in the [quickstart create-a-user-account](https://docs.stormpath.com/rest/product-guide/latest/quickstart.html#create-a-user-account) section is inaccurate.

It shows:

``` command
curl --request GET \
  --user $SP_API_KEY_ID:$SP_API_KEY_SECRET \
  --header 'content-type: application/json' \
  --url "https://api.stormpath.com/v1/applications/1gk4Dxzi6o4PbdlEXampLE/accounts"
  --data '{
  "givenName": "Joe",
  "surname": "Stormtrooper",
  "username": "tk421",
  "email": "tk421@stormpath.com",
  "password":"Changeme1",
  }'
```

but the GET should be a POST

**Comment by jakubvul** [comment]
Good catch @artburkart, I'll get that fixed ASAP!

**Comment by jakubvul** [comment]
Change has been made and deployed!

**Comment by artburkart** [comment]
Ah! And now I understand why I couldn't find the docs in the repo. Was looking at the markdown rendering of the rst file, which hid the code. Cheers
