### ISSUE TITLE
SAML REST Documentation

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#13]
https://stormpath.atlassian.net/wiki/display/AM/Stormpath+as+a+SAML+Service+Provider

**Comment by jakubvul** [comment]
- [x] Update Application resource with new SAML-specific `authorizedCallbackUris` Array
- [x] Update Application resource to show that it now has a "samlPolicy" object associated with it
- [x] Update Provider resource with new SAML-specific attributes
- [x] "Add Authenticating Against a SAML Directory" section to AuthN chapter

**Comment by jakubvul** [comment]
SAML doc is live as of 2016-12-16: http://docs.stormpath.com/rest/product-guide/latest/005_auth_n.html#e-authenticating-against-a-saml-directory

**Comment by lhazlewood** [comment]
Thanks Jakub.  Minor note:

In the 'Stormpath SAML Flow' diagram, we should rename 'Service Provider'
to 'Your Application' to make it obvious.  Stormpath is seen as a Service
Provider by the IDP, and that muddies the waters a bit.  By clearly
labeling it 'Your Application', there is no confusion.

## 

Les
@lhazlewood

**Comment by jakubvul** [comment]
Fair enough. Change will be reflected next time we deploy docs.
