### ISSUE TITLE
SAML Response JWT documented improperly?

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-documentation#131]
https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#saml-response-jwt

https://stormpath.zendesk.com/agent/tickets/7502

https://github.com/stormpath/stormpath-sdk-java/commit/f26e59a0ed68ceb2631791a48c11a9cc3d90bd54

Looks like we're moving from `aud` being the key id to `KID`. 

Still works for ID Site, but looks like not so for SAML? 

Also see https://github.com/stormpath/stormpath-sdk-dotnet/issues/176

**Comment by jakubvul** [comment]
Are you referring to the JWT that you generate and pass to Stormpath?

https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#step-1-generate-a-jwt

**Comment by edjiang** [comment]
Nope, the result JWT. 

For instance, here's something I get back from ID Site: 

``` Javascript
HEADER
{
  "typ": "JWT",
  "alg": "HS256",
  "kid": "1NI4IH70OV7V7UR6B9MYHP20G"
}
BODY
{
  "iss": "https://nimble-bobcat.id.stormpath.io",
  "sub": "https://api.stormpath.com/v1/accounts/7ZbV2MtrCH9Oh6QKKxoyZq",
  "aud": "1NI4IH70OV7V7UR6B9MYHP20G",
  "exp": 1462913443,  // Tue May 10 2016 13:50:43 GMT-0700 (PDT)
  "iat": 1462913383,  // Tue May 10 2016 13:49:43 GMT-0700 (PDT)
  "jti": "5dpyqxee0CMBf2078d3AHp",
  "irt": "e39f043d-0ef1-4701-8140-c55dfcdaae33",
  "state": "",
  "isNewSub": false,
  "status": "AUTHENTICATED",
  "cb_uri": "http://localhost:3000/idSiteResult"
}
```

But check the Zendesk for what someone's getting back from the SAML stuff. @nbarbettini
