### ISSUE TITLE
Syntax Error in VB.net literal block

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#135]
`quickstart.rst:241: WARNING: Could not lex literal_block as "vbnet".`

File in question: `initialize_client.vb`

**Comment by nbarbettini** [comment]
Is this on branch `the_one_product_guide` latest?

**Comment by jakubvul** [comment]
It is.

**Comment by nbarbettini** [comment]
Fixed in 5248767e03eb41c70c495727288ea49c33fd7607
