### ISSUE TITLE
Show language in header

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-documentation#139]
It would be easier to tell different versions of the One Product Guide apart if this header:

![image](https://cloud.githubusercontent.com/assets/7525482/15413142/4c9486ec-1de2-11e6-9439-f6f33133178d.png)

Was updated to **Stormpath C# Documentation** (for example).

This should be possible by some magic in `conf.py`:

``` python
if tags.has('csharp'):
    lang_name = u'C#'

elif tags.has('vbnet'):
    lang_name = u'Visual Basic'

elif tags.has('nodejs'):
    lang_name = u'Node.js'

else:
    raise ValueError('Unknown language tag.')

# General information about the project.
project = u'Stormpath %s Documentation' % lang_name

# Automatically added to the end of every source file
# so |language| can be used as a substitution in the RST files
rst_epilog = """
.. |language| replace:: %(lang_name)s
""" % { 'lang_name': lang_name }
```

There might be other ways of doing this, but this is what I got working for the ASP.NET docs.

**Comment by jakubvul** [comment]
I was just thinking about this yesterday! Could you make a PR with your `conf.py` changes?

**Comment by jakubvul** [comment]
What about the version? Because "V1" is definitely misleading. I've just removed it for now...
