### ISSUE TITLE
Add note about the base url about different environments for enterprise and private deployments

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#16]
https://docs.stormpath.com/rest/product-guide/latest/reference.html#base-url

**Comment by jakubvul** [comment]
Added following language:

All URLs referenced in the API documentation begin with the following base URL:

  `https://api.stormpath.com/v1/`

This is the base URL for Stormpath's public API. If you are using an Enterprise deployment, your base URL will instead be:

  `https://enterprise.stormpath.io/v1/`

And if you have a private Stormpath deployment, the base URL could be a completely custom URL, or simply: 

  `https://yourOrganization.stormpath.io/v1/`
