### ISSUE TITLE
Update Okta SAML docs for Attribute Name Format

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-documentation#170]
Docs here: https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#id30

The Attribute Name Format fields need to have a valid `urn` in the Stormpath configuration: `urn:oasis:names:tc:SAML:2.0:attrname-format:basic`

![image](https://cloud.githubusercontent.com/assets/364562/15844382/e5218280-2c37-11e6-92ed-df2149bf46d5.png)

Assuming the Name Format type on the Okta side is `Basic`

![image](https://cloud.githubusercontent.com/assets/364562/15844400/0d31912a-2c38-11e6-9717-672c7c60cd54.png)

**Comment by jakubvul** [comment]
So I did some checking, and:
- If you specify an "Attribute Name Format" in your Stormpath mapping, it must match whatever it is set as in Okta
- If you leave the "Attribute Name Format" blank, the mapping will still go through successfully. 

So for example:

![screen shot 2016-06-23 at 2 49 31 pm](https://cloud.githubusercontent.com/assets/4551905/16315792/bdd79094-3951-11e6-89fd-904fd7c60548.png)

Along with this:

![screen shot 2016-06-23 at 2 50 12 pm](https://cloud.githubusercontent.com/assets/4551905/16315816/d38dba4e-3951-11e6-98a0-95e7ee878de5.png)

Works just fine:

![screen shot 2016-06-23 at 2 50 46 pm](https://cloud.githubusercontent.com/assets/4551905/16315847/e931a5f4-3951-11e6-80e3-d3a5a067ee65.png)
