### ISSUE TITLE
PHP SDK Documentation - Final Pass

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#173]
Going to give the PHP SDK Documentation a final read through, then pass it on to @bretterer for any fixes and final approval.
- [x] In Account Management, section **3.6.2. Customizing Stormpath Email Templates** doesn't have any PHP content. I forgot to add a `todo` there. 
- [x] in Authentication, section **Step 3: Access an Account with Google Tokens**, there's a blank section for PHP just above **4.3.2. Facebook**. I've added a `php.todo`.
- [x] Same goes for Facebook, the empty section is just above **4.3.3. Github**
- [x] The Get Default Relay State with Extras section in Authentication is missing any PHP content. 
  Right now it says `A request including these optional properties looks like this:` and then it's just blank. I've added a `(php.todo)` to line 4147, just above **Step 6: Add the SAML Directory as an Account Store**.

**Comment by jakubswiatczak** [comment]
@bretterer : In Account Management, section **3.6.2. Customizing Stormpath Email Templates** doesn't have any PHP content. I forgot to add a `todo` there.

**Comment by jakubswiatczak** [comment]
@bretterer : in Authentication, section **Step 3: Access an Account with Google Tokens**, there's a blank section for PHP just above **4.3.2. Facebook**. I've added a `php.todo`.

**Comment by jakubswiatczak** [comment]
The Get Default Relay State with Extras section in Authentication is missing any PHP content. 

So right now it says `A request including these optional properties looks like this:` and then it's just blank.

This needs to be fixed. I've added a `(php.todo)` to line 4147, just above **Step 6: Add the SAML Directory as an Account Store**.

**Comment by jakubvul** [comment]
Alright @bretterer , my final pass is done. Can you generate it and have one final glance over the output to make sure you're happy with it?
