### ISSUE TITLE
Update Access/Refresh Token TTL

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#180]
https://stormpath.atlassian.net/browse/AM-3208

**Comment by jakubvul** [comment]
We only really mention the maximum value for the TTL in the Authentication Chapter, so it needs to be updated there.

However, while I'm at it, we should add the min/max values to the Reference chapter as well.

**Comment by jakubvul** [comment]
Specifically, this affects:

**/v1/oAuthPolicies/$APPLICATION_ID**

`accessTokenTtl`
`refreshTokenTtl`

The text in the **Configuring Token-Based Authentication** section of Authentication.
