### ISSUE TITLE
Include section on local ID Site in the new docs

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#196]
The [latest docs](https://docs.stormpath.com/rest/product-guide/latest/idsite.html#idsite-set-up) on ID Site should include instructions on how to set up ID Site locally. This is listed [here](http://docs.stormpath.com/guides/using-id-site/#getting-set-up) in the old docs. Also might want to consider adding section as a subheader in the new docs -- we do get asked about it a lot!

**Comment by jakubvul** [comment]
That section you linked to actually instructs you on how to modify ID Site, not host it locally.

**Comment by jakubvul** [comment]
Is this what you were looking for? https://docs.stormpath.com/rest/product-guide/latest/idsite.html#idsite-hosting

**Comment by mdeggies** [comment]
I think https://github.com/stormpath/stormpath-console-guide/issues/35 is what I was getting at, but I don't remember. Lol
