### ISSUE TITLE
Small typo in REST Docs

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#198]
There's a small typo in the REST docs on the ['Create a User Account' page](https://docs.stormpath.com/rest/product-guide/latest/quickstart.html#create-a-user-account). 

The code sample looks like this:
![screen shot 2016-06-21 at 11 25 54 am](https://cloud.githubusercontent.com/assets/12939567/16241540/fab83730-37a2-11e6-93b3-eebaaa9c4756.png)

As you can see, there's an extra comma after the password field. Not a big deal, but it's thrown some of our users off. The error they're receiving is "Missing or invalid request body": 

![screen shot 2016-06-21 at 11 28 53 am](https://cloud.githubusercontent.com/assets/12939567/16241637/6e8a5e5e-37a3-11e6-8ff3-2657c7338a36.png)

The code sample should be updated to look like this: 
![screen shot 2016-06-21 at 11 26 50 am](https://cloud.githubusercontent.com/assets/12939567/16241567/1709298a-37a3-11e6-8e5a-ace952aad35e.png)

**Comment by jakubvul** [comment]
On it!
