### ISSUE TITLE
client_credentials grant flow needs to use the REST API

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#214]
Code written to support creating access tokens locally MUST use the REST API endpoint: https://stormpath.atlassian.net/browse/AM-2895

**Comment by jakubvul** [comment]
This requires:

#### Authentication
- [ ] Not-insignificant updates to **Generating an OAuth 2.0 Access Token** section

**Comment by jakubvul** [comment]
This looks like it will require updating the same sections as #216.

**Comment by jakubvul** [comment]
@nbarbettini and @bretterer this requires updates to your sections under Generating an OAuth 2.0 Access Token.

**Comment by jakubvul** [comment]
Interestingly we already noted that we support the Client Credentials Grant Type in the guide, so the primary update for the REST guide was just this bit of text:

```
So for the **Client Credentials Grant Type**, you pass the **API Key ID** and **Secret**:

``grant_type=client_credentials&apiKeyId=2ZFMV4WVVexample&apiKeySecret=XEPJolhnMYexample``

And for the **Password Grant Type**, you pass the **username** and **password**:

``grant_type=password&username=tom%40stormpath.com&password=Secret1``
```
