### ISSUE TITLE
Add support for organiationNameKey for oauth token exchange

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#216]
https://stormpath.atlassian.net/browse/AM-3287

**Comment by jakubvul** [comment]
Auth_n chapter, section **Generating an OAuth 2.0 Access Token:**

@nbarbettini You have a note here about generating a token against a particular Account Store:

> use the `SetAccountStore()` method

Not sure if this needs updating if you wanted to generate a token against a particular Organization.

@bretterer There's no mention of generating a token against a specified Account Store. Should there be?

**Comment by jakubvul** [comment]
Updated this note:

```
  .. note::

    Just like with logging-in a user, it is possible to generate a token against a particular Application's Account Store or Organization. To do so, specify the Account Store's ``href`` or Organization's ``nameKey`` as a parameter in the body::

      grant_type=password&username=tom@stormpath.com&password=Secret1&accountStore=https://api.stormpath.com/v1/directories/2SKhstu8Plaekcai8lghrp

      grant_type=password&username=tom@stormpath.com&password=Secret1&organizationNameKey=companyA
```
