### ISSUE TITLE
stormpath_token can exchange for REGISTERED status

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#217]
Any code that was written to be a bandaid over stormpath_token not handling the REGISTERED status can be remove to use the endpoint: https://stormpath.atlassian.net/browse/AM-3291

**Comment by jakubvul** [comment]
Already documented [as of 2016/06/20](https://docs.stormpath.com/rest/product-guide/latest/changelog.html#id3).
