### ISSUE TITLE
SAML directory creation

### ISSUE THREAD

**Issue by dogeared** [stormpath/stormpath-documentation#23]
Step 2 of http://docs.stormpath.com/rest/product-guide/latest/005_auth_n.html#e-authenticating-against-a-saml-directory

should call out the `/v1/directories` endpoint and not `/v1/directories/$DIRECTORY_ID/provider`

**Comment by jakubvul** [comment]
More specifically, you have to create the entire SAML Directory with all of the SAML-specific information in one fell swoop, instead of just updating the Provider resource.

**Comment by jakubvul** [comment]
We also have invalid JSON for the x509 certificate. This is the accurate JSON

```
{
  "ssoLoginUrl":"https://yourIdp.com/saml2/sso/login",
  "ssoLogoutUrl":"https://yourIdp.com/saml2/sso/logout",
  "encodedX509SigningCert":"-----BEGIN CERTIFICATE-----\n...Certificate goes here...\n-----END CERTIFICATE-----",
  "requestSignatureAlgorithm":"RSA-SHA256"
}
```
