### ISSUE TITLE
Handle 404 on Reference.html when switching languages

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#234]
The best way I can think to handle this is to have language specific sections for this page that will reference in an iframe the API reference for that particular language, keeping the sphinx TOC for navigation.

**Comment by omgitstom** [comment]
I see this is also happening on other pages (Configuration, switching from PHP to REST), I think we need some sort of general ‘’This section is not applicable to the language you selected” page to stop it from 404ing.

**Comment by jakubvul** [comment]
Fixed. All non-REST urls for `reference.html`, as well as REST `configuration.html` redirect to a special error page.

Example: https://docs.stormpath.com/rest/product-guide/latest/configuration.html
