### ISSUE TITLE
Linking to broken page 

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#238]
[On this page in the PHP docs](https://docs.stormpath.com/php/product-guide/latest/idsite.html), we link to  http://imperialxchange.com/ which has broken functionality. We should either fix that site to continue using it, or link to a different web-app for demos.

**Comment by jakubvul** [comment]
![screen shot 2016-07-12 at 12 15 54 pm](https://cloud.githubusercontent.com/assets/4551905/16774562/876a5b9e-482a-11e6-8b56-ce56001e8fe4.png)
![screen shot 2016-07-12 at 12 16 10 pm](https://cloud.githubusercontent.com/assets/4551905/16774563/89b617bc-482a-11e6-96e8-49dff6a322bb.png)

**Comment by jakubvul** [comment]
Website has been fixed.
