### ISSUE TITLE
Sample Request : /v1/applications/{uid}/LoginAttempts

### ISSUE THREAD

**Issue by rbhojan** [stormpath/stormpath-documentation#243]
The Sample request for LoginAttempts in the Applications Endpoint is missing a comma after the second attribute - "value". 

Should be :

{
    "type": "basic",
    "value": "YmFzZTY0LWVuY29kZWQtbG9naW4tYW5kLXBhc3N3b3Jk",
    "accountStore": {
         "href": "https://api.stormpath.com/v1/groups/$YOUR_GROUP_ID"
   }
}

But currently is : 

{
    "type": "basic",
    "value": "YmFzZTY0LWVuY29kZWQtbG9naW4tYW5kLXBhc3N3b3Jk"
    "accountStore": {
         "href": "https://api.stormpath.com/v1/groups/$YOUR_GROUP_ID"
   }
}

<img width="1275" alt="screen shot 2016-07-15 at 2 11 57 pm" src="https://cloud.githubusercontent.com/assets/6137543/16888760/f02650e8-4a96-11e6-96c6-b9696f2edaa7.png">

**Comment by jakubvul** [comment]
Thanks for bringing this to our attenting @rbhojan! I'll get a fix pushed up right away.
