### ISSUE TITLE
Python - Product Guide Errata

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#262]
1. Under the Directories section of Account Management, you put `.. todo:: Add a link to the API docs.` (line 52) Would that be this https://docs.stormpath.com/python/apidocs/stormpath.resources.html#module-stormpath.resources.directory ?
2. Also in Account Management (line 2349):

```
.. only:: python
  To modify the emails that get sent during the password reset workflow, all you have to do is send an HTTP POST with the desired property in the payload body. For more information about Email Templates, see the `Email Templates section <https://docs.stormpath.com/rest/product-guide/latest/reference.html#ref-emailtemplates>`__ of the Reference chapter.

.. only:: rest or vbnet or csharp or php

  To modify the emails that get sent during the password reset workflow, all you have to do is send an HTTP POST with the desired property in the payload body. For more information about Email Templates, see the `Email Templates section <https://docs.stormpath.com/rest/product-guide/latest/reference.html#ref-emailtemplates>`__ of the Reference chapter.
```

Is there anyone we can just add `or python` to that second bracket? Is there supposed to be something different between them?
1. In Configuration, there's a `(python.todo)` under Using a Different Environment, line 234. If that section isn't relevant, you can just delete the todo. 
2. Same as last point, but under Inline Code, line 879. Again, if not relevant, please just delete it.

**Comment by rdegges** [comment]
Heyo!
1. No, the existing Python API docs need to be fixed / re-published. They are really out of date (old builds), that's why I added the todo.
2. Yes! Would you simplify that logic? They look the same, so I think I made a mistake there, sorry!

**Comment by jakubvul** [comment]
...and the other 1 and 2? Gotta love Markdown's autonumbering. 

Just give me the go-ahead and I can delete them.

**Comment by rdegges** [comment]
Ok, the first #1, yes. I just fixed it in a PR. The second one, that needs to stay. I just pushed it into a PR for ya.
