### ISSUE TITLE
Small addition to OneLogin SAML Docs

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#278]
https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#step-4-configure-your-service-provider-in-onelogin

Section 4 Part 2 needs some clarification. It says: "Copy your Directory’s “Assertion Consumer Service URL” into both the “ACS (Consumer) URL Validator” and “ACS (Consumer) URL” fields."

We need to explain that you need to click on the 'Directories' tab in Stormpath, click on the SAML Directory you just created, under 'SAML Configuration' click on the 'Identity Provider' tab and then copy the Assertion Consumer Service URL from that into the OneLogin config.

**Comment by jakubvul** [comment]
Directly above this:

```
3.2. Gather Your SAML Directory Information
Find and click on your new SAML Directory.
Copy the “Assertion Consumer Service URL” found in the “SAML Identity Provider Configuration” section
Note

You should leave this page open, since you’ll be back here in Step 4.
We will now input this value into the Identity Provider.
```
