### ISSUE TITLE
Authorization / Multitenancy Details

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#28]
Questions to answer:
- [x] Why use one directory with groups to model out authorization and multi-tenancy? //One group for tenant

One directory gaurentees account uniqueness on email and username.  If you need to gaurentee that one account is unique in your directory, you must go with this approach.  Groups that represent tenants (such as org.cocacola) and / or roles (such as role.admin).  Organizations can be used to model out multi-tenancy, and the tenant group would be added to the organization.

For example:
Application--ASM-->Organization--OASM-->Group

If you need to query an account for it's org or roles, Stormpath recommends using a resource naming convention for querying.

account->groups({'name':'tenant.*'}) //Gets groups that represent tenant membership
account->groups({'name':'role.*'}) //Gets groups that represent role membership
- [x] Why use multiple directories with their own groups to model out authorization and multi-tenancy? //One directory per tenant

If you have requirements where:
- Each org has its own password strength policy
- Each org has different emails to send (for example, one tenant doesn't do email verification)
- Each account in an org must have a seperate username and password
- Each organization has different groups and roles

You should model out Stormpath with one directory per tenant.
Application--ASM-->Organization--OASM-->Directory

This will give you the control that you need for your multitenancy requirements since password policies / emails / groups / account uniqueness is associated with the directory.

**Comment by brentstormpath** [comment]
I'd additionally include:
- [x] A section on tenant identifiers. What they are and how to implement them (the current use case guide does this well).
- [x] Briefly cover that the tenant still needs to be represented as an Account Store even when using Organizations
- [x] On the Role based authorization section, examples of what Role Groups look like in an application that's using the Group-per-tenant approach.

**Comment by jakubswiatczak** [comment]
**organizationAccountStoreMapping** is not documented! It maps Organization to a Directory or Group

Also, probably shouldn't refer to Organizations as "Account Stores", because they're really not.

**Comment by lhazlewood** [comment]
Organizations are definitely AccountStores from an Application's perspective - they're just 'virtual' account stores.

**Comment by jakubvul** [comment]
@lhazlewood I've captured that in the API Reference chapter:

> A pseudo-Account Store that can :ref:`be mapped to an Application <create-asm>` (just like a Directory or Group) for the purposes of user login. Unlike Directories and Groups, however, they do not themselves own Accounts, and Users and Groups cannot be associated to them without also being associated with a Directory.

As well as in the Multitenancy chapter:

> Although Organizations do not themselves own Accounts in the same way as Directories and Groups, they can be mapped to Applications as Account Stores for the purposes of user log in. This means that they can be used as, among other things, a single-point of access control to an Application.

**Comment by lhazlewood** [comment]
Beautimous!
