### ISSUE TITLE
Account Schema Configuration

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#289]
https://stormpath.atlassian.net/wiki/display/AM/Loosening+Data+Model+Requirements AM-2067

**Comment by jakubvul** [comment]
We want to allow people to configure which fields are required for new Accounts on a per-Directory basis. To accomplish this, Directories now contain a new collection:

```
"accountSchema":{
  "href":"https://api.stormpath.com/v1/schemas/4YieniebnB9QRGNexample"
}
```

URL: `/v1/schemas/$SCHEMA_ID`

This is the accountSchema object itself, with "fields" expanded (these are currently the only possible fields):

```
{
  "href":"https://api.stormpath.com/v1/schemas/4YieniebnB9QRGNuzipZR9",
  "createdAt":"2016-08-02T19:44:54.569Z",
  "modifiedAt":"2016-08-02T19:44:54.569Z",
  "fields":{
    "href":"https://api.stormpath.com/v1/schemas/4YieniebnB9QRGNuzipZR9/fields",
    "offset":0,
    "limit":25,
    "size":2,
    "items":[
      {
        "href":"https://api.stormpath.com/v1/fields/4YienlyghlSP45TmBygq3D",
        "createdAt":"2016-08-02T19:44:54.569Z",
        "modifiedAt":"2016-08-02T19:44:54.569Z",
        "name":"givenName",
        "required":true,
        "schema":{
          "href":"https://api.stormpath.com/v1/schemas/4YieniebnB9QRGNuzipZR9"
        }
      },
      {
        "href":"https://api.stormpath.com/v1/fields/4YienpIlcLlNguZdOEY6fH",
        "createdAt":"2016-08-02T19:44:54.569Z",
        "modifiedAt":"2016-08-02T19:44:54.569Z",
        "name":"surname",
        "required":true,
        "schema":{
          "href":"https://api.stormpath.com/v1/schemas/4YieniebnB9QRGNuzipZR9"
        }
      }
    ]
  },
  "directory":{
    "href":"https://api.stormpath.com/v1/directories/2SKhstu8Plaekcai8lghrp"
  }
}
```

**Comment by jakubvul** [comment]
- [x] Add new section to Account Management
- [x] Update Reference chapter section on Directories
- [x] Update all Directory JSON examples
- [x] Add information somewhere that, for any Directories created after August 13 2016, `givenName` and `surname` are not mandatory by default.

**Comment by jakubvul** [comment]
Admin Console UI right now does NOT recognize this. The front-end validation right now requires everything that it's always required by default.
