### ISSUE TITLE
Account Management

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#3]
- [x] 4a `The first question that we need to address is how we are going to model our users inside the Stormpath database.` Stormpath isn't a database, I think this should be worded as model our users inside Stormpath. 
- [x] 4b table - Refresh tokens are also JSON web tokens
- [x] 4b table - The access tokens and refresh tokens are a collection of un-expired / un-revoked tokens that are associated with the account.
- [x] 4b `Importing Accounts with Non-MCF Hash Passwords`  Stormpath should recommend that if we can not import the password that they set a large randomly generated string as the password and force the user through a password reset flow using the API
- [x] 4c `How to Search Accounts`  This section needs to be fleshed out with the information and is missing datetime search :)
- [x] 4d `Password Reset` `minUpperCase` and `minDiacritic` are missing the accents
- [x] 4d `Password Reset` `Enable Password Reset Emails` body is messed up

**Comment by jakubvul** [comment]
Fixed as part of 2ebaeb4.
