### ISSUE TITLE
SAML Configuration Guide

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#30]
We need step by step configuration with the following:
- [x] OneLogin
- [x] Salesforce
- [x] Okta
- [x] Ping Identity: https://github.com/stormpath/stormpath-documentation/issues/114
- [x] ADFS with SAML 2.0: https://github.com/stormpath/stormpath-documentation/issues/45

**Comment by jakubvul** [comment]
This would probably be standalone, not part of the Product Guide.

**Comment by omgitstom** [comment]
1. Start with the IdP
   Get to the login url, logout url, signing cert
2. Go into Stormpath Admin and configure the Directory
   
   2.1. Get the entity ID, ACS, cert (optional)
3. Go back to the IdP and configure with entity ID / Signing Cert
4. Go into Stormpath and associated a application with the directory and add the callback Uri for the application

**Comment by jakubvul** [comment]
- SAML Set-Up, end-to-end, with the Admin Console
- You have a Stormpath Account, Advanced level + an account with an IdP that supports SAML + an "Application" already set-up with your IdP (e.g. a Salesforce "Connected App")
- The documentation stops at the point where they CAN actually authenticate with SAML
- Attribute mapping and testing would be separate

**Comment by jakubvul** [comment]
SAML Attribute Mapping, written-up and verified working:
- [x] Salesforce
- [x] OneLogin
- [x] Okta
- [x] Ping

**Comment by blackenedstrang** [comment]
Hi guys, sorry if it is not right place, but could you please help me with two questions:
1. What has happened with forth original option 'ADFS with SAML 2.0', are you still going to create guide for it?
2. Is it possible to connect Stormpath to external Active Directory via external ADFS 2.0 instead of using Stormpath agent? This is in order to implement federated SSO scenario in situation when we are not allowed to install 3rd part tools in our client's network.

**Comment by omgitstom** [comment]
Hi @blackenedstrang 

I manage Product @ Stormpath. 
1. Yes, we are you can track it here: https://github.com/stormpath/stormpath-documentation/issues/45 There has been a few other higher priority items, but we are still planning on adding this documentation
2. From our initial research into ADFS, this is possible, we did not test ADFS 2.0, but if it supports SAML 2.0, it should work.

Thanks,
Tom

**Comment by jakubvul** [comment]
@blackenedstrang You can find our ADFS configuration instructions here: https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#active-directory-federation-services

**Comment by blackenedstrang** [comment]
@jakubswiatczak Thanks for informing.
