### ISSUE TITLE
Small typo in 'Consuming the token'

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#300]
Small typo here:

https://docs.stormpath.com/rest/product-guide/latest/accnt_mgmt.html#verifying-the-email-address-consuming-the-token

It should be token instead of tokens (I think): 

```
POST /v1/accounts/emailVerificationTokens/6YJv9XBH1dZGP5A8rq7Zyl HTTP/1.1
Host: api.stormpath.com
Content-Type: application/json;charset=UTF-8
```

**Comment by mdeggies** [comment]
Err wait. Isn't it just: 

https://api.stormpath.com/emailVerificationTokens?sptoken=$TOKEN

**Comment by jakubvul** [comment]
It is both.

`emailVerificationTokens?sptoken=$TOKEN` is the link for browsers that we send via email.

`accounts/emailVerificationTokens/$TOKEN` is an endpoint off of the Account resource that you can `POST` the token to in order to verify an email address.
