### ISSUE TITLE
409 errors when setting authorized callback URI's

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#303]
Re: https://trello.com/c/utbkmuz5/27-409-errors-when-setting-the-authorized-callback-uris

409 errors when setting authorized callback URI's

This could be caused by too many callback URI's. Stormpath has a limit of 4000 characters for total callback URI's. Using wildcards can definitely help minimize the # of callback URI's and ensure that everything works as expected.

**Comment by jakubvul** [comment]
Good to know! Added this information to both the One Product Guide and Admin Console Guides.
