### ISSUE TITLE
REST Guide - Feedback on Search

### ISSUE THREAD

**Issue by rbhojan** [stormpath/stormpath-documentation#31]
The section on Matching Logic, mentions about "case-insensitive" value, except for point 4.
"An asterisk at the end AND at the beginning of the value indicates the value is contained in the string"
Please check the attachment for screenshot. 
<img width="1154" alt="new search api" src="https://cloud.githubusercontent.com/assets/6137543/12098277/13b067b4-b2d6-11e5-9fc3-c832d293ca9d.png">

**Comment by jakubvul** [comment]
Moved "case-insensitive" into a note, which should make it easier to read.
