### ISSUE TITLE
ADFS small change

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#324]
On step 5 here, https://docs.stormpath.com/console/product-guide/latest/appendix-saml.html#add-a-relying-party-trust, it's noted that you can use any display name you wish. But when you reference that name later in 3.4.1 and 3.4.4, I think the display name is being referred to as 'api.stormpath.com'.

**Comment by mdeggies** [comment]
Also I am a total noob when it comes to ADFS, so on step 5-5.1, I would really like to see an explicit example of adding a claim:

"As an example, you might have a claim type of 'given-name' in AD/LDAP that you want to be mirrored in Stormpath. You can achieve this clicking on 'Add Rule' and selecting 'Send LDAP Attributes as Claims'. Select 'Active Directory' as your attribute store. In the mapping table, you can add your rules. Following the above example, if one of your AD/LDAP attributes is 'given-name', you can map that to Stormpath's 'firstName' attribute. When your users first log in with their AD credentials and mirrored accounts are created for them in Stormpath, you should see the 'firstName' attribute matching their 'given-name' in AD/LDAP."

**Comment by jakubvul** [comment]
In future, please put this in the correct repo: https://github.com/stormpath/stormpath-console-guide/issues

**Comment by jakubvul** [comment]
Fixed here https://github.com/stormpath/stormpath-console-guide/commit/012e74e3ec2d3b7bb272451296ad1d2b184ac3a7
