### ISSUE TITLE
Clarity in Product Guide quickstarts

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#327]
Reference: https://docs.stormpath.com/nodejs/product-guide/latest//quickstart.html#create-an-api-key-pair

I've gotten 2 questions about this so far, and I imagine some people in other languages are having trouble as well -- we reference creating a .stormpath directory and moving the apiKey.properties file into it. The client instance searches there for the API key and all is good from then on...

But, the name of the file that you download when you create an API key is called apiKey-$API_KEY_ID.properties, not apiKey.properties. 

We need to put a note in here about that.. my suggestion:

```
$ mkdir ~/.stormpath
$ mv ~/Downloads/apiKey-$API_KEY_ID.properties ~/Downloads/apiKey.properties
$ mv ~/Downloads/apiKey.properties ~/.stormpath/
```

I honestly don't even know if that will be clear enough.. thoughts?

**Comment by jakubvul** [comment]
How about we compress those 2 steps into 1:

`mv ~/Downloads/apiKey-{$API_KEY_ID}.properties ~/.stormpath/apiKey.properties`

?
