### ISSUE TITLE
Document "issuer" for MFA

### ISSUE THREAD

**Issue by edjiang** [stormpath/stormpath-documentation#333]
```
{
  "type":"google-authenticator",
  "accountName": "Stormpath Two-Factor Demo",
  "issuer": "Demo App"
}
```

Issuer property isn't documented.

**Comment by jakubvul** [comment]
https://docs.stormpath.com/rest/product-guide/latest/reference.html#factor

**Comment by jakubvul** [comment]
When POSTing to the `accounts/accountID/factors` endpoint “issuer” makes a name actually show up in Google Authenticator. - Ed
