### ISSUE TITLE
Add section on changing tenant ownership

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#337]
I realized this should probably be in the admin console guide (here) instead of the kb 

http://docs.stormpath.com/console/product-guide/latest/administration.html#managing-tenant-administrators

https://stormpath.zendesk.com/hc/en-us/articles/228885547

**Comment by jakubvul** [comment]
https://github.com/stormpath/stormpath-console-guide/commit/9fb3dbdc6149663f80304cb597807621798831a8
