### ISSUE TITLE
Add emailVerificationStatus to Account

### ISSUE THREAD

**Issue by jhericks** [stormpath/stormpath-documentation#340]
See [Email Verification Account Linking Fixes](https://stormpath.atlassian.net/wiki/display/AM/Email+Verification+Account+Linking+Fixes) for details.

This new property is not live yet, but will be with this week's release.

**Comment by jakubvul** [comment]
https://github.com/stormpath/stormpath-documentation/commit/3ba11eb5a4fb29c5ac4454f01e6098610ce4e06e
