### ISSUE TITLE
Section on using different character sets

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#358]
Enterprise customer request: 

"\* Is there any documentation about using other character sets besides english and/or localizating into another language using storm path? 
- How are these characters encoded? Is it unicode or unicode encoded as UTF-8 or another encoding? 
- Related to the last question, how do we search this information? I image it will vary based on the encoding.

I look forward to any future articles/docs that are ever written up on this subject."

I searched and was able to find that Stormpath expects and uses UTF-8, and that the only characters we do not currently support are 4 byte UTF8 characters, so I passed that along, but it would be nice to cover this more extensively in the docs somewhere.

**Comment by rdegges** [comment]
The answer to this is UTF-8. Everything should always be UTF-8 in all cases everywhere =) No exceptions.
