### ISSUE TITLE
Migrate from Product to Admin Console Guide 

### ISSUE THREAD

**Issue by mdeggies** [stormpath/stormpath-documentation#361]
"How social auth works" and stuff like that should be added to the Admin Console guide and removed from the Product Guide. 

https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#how-social-authentication-works

**Comment by jakubvul** [comment]
The instructions specifically show how to set up social login via REST/Java/etc, so absolutely they should not be. =)

On top of that, the Admin Console Guide already has the instructions: https://docs.stormpath.com/console/product-guide/latest/directories.html#create-a-social-directory
