### ISSUE TITLE
Social Login V2

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#377]
Documentation for this feature needs to be completed for release alongside the new functionality.

**Client API**

- [x] `/authorize` (https://github.com/stormpath/stormpath-client-api-guide/issues/1)
- [x] `/authorize/callback` endpoint 

**AuthN Chapter**

- [ ] Vanilla social login now includes an optional `redirectUri` URL parameter
- [x] OAuth social login now includes an optional `redirectUri` URL-encoded form parameter
- [x] However, we should remove the old *Step 3* from the different Social Login write-ups and replace it with instructions for using the new `/authorize` endpoint instead. Documentation of the old Vanilla Social Login (to the `/accounts` endpoint) should only be included in a note to the new instructions.
- [x] We also need the above note to mention the old way of generating an OAuth token with the social grant type, and link to it. At the same time, the OAuth instructions should link to the new hotness. 

- [x] You can now map what's returned in `userInfo` to Account attributes via `userInfoMappingRules`
- [x] You can now define exactly what scopes you're requesting from each Provider. These are stored in the Directory Provider in a `scope` array

**Reference Chapter**

- [x] Account `providerData` now includes a `userInfo` object
- [x] Directory `provider` now has a `scope` array
- [x] Directory `provider` also has a `userInfoMappingRules` array

**Comment by omgitstom** [comment]
There is also:

Twitter
Generic OAuth 2.0

**Comment by jakubvul** [comment]
OAuth generation section needs proper link to Client API Guide once that is complete and deployed.

**Comment by edjiang** [comment]
Make sure to note:

Positive responses for the `stormpath_token` response type occur in the `jwtResponse=` form which you exchange

Negative responses occur in the standard OAuth form: `error=&error_description=` like defined in this section of the RFC:

https://tools.ietf.org/html/rfc6749#section-4.1.2.1
