### ISSUE TITLE
About section feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#4]
- [x] What you can do with Stormpath: - Stormpath is more than a REST API, it is a REST API, open source language specific SDKs, and framework integrations (like express / spring boot).  and a admin console
- [x] Who should use Stormpath: userbase - should be two words
- [x] Who should use Stormpath: You are a big organization who would like to use Stormpath.  We support private deployments, not on premise
- [x] Who should use Stormpath: You might not want to use Stormpath if... This section seems unneeded, I could actually argue that you can use stormpath if your application is internal-only usage, or if you aren't worried about security, or if you aren't worried about availability / redundancy, and even if you want to roll your own custom user authentication. 
- [x] The Stormpath Data Model: Tenant - The Tenant resource represents the Stormpath customer.  This is somewhat confusing.  Maybe we can modify it a bit to make it sound a little more correct. The Tenant resource represents a Stormpath customer...This space is represents your Tenant resource in Stormpath.
- [x] The Stormpath Data Model: Both Directories and Groups are Account Stores.  Account Stores can be mapped to Applications to allow your accounts to log into a particular application (an important point!)
- [x] We might want to talk about collection resource more in depth in this section

**Comment by jakubvul** [comment]
@omgitstom: How about this for Tenant - 

> When you sign up for Stormpath, a private data space is created for you, which is represented as a **Tenant** resource in the Stormpath REST API. As a Stormpath customer, you own your Tenant resource and everything in it – Applications, Directories, Accounts, Groups, and so on.

As for the first point: The other things that Stormpath offers are explained just a few lines later. At its core, though, it is an API service, whereas all of the other offerings are optional. I think that, taken as a whole, the section answers the "What Is Stormpath?" question very well. 

> Stormpath is a hosted API service for creating and managing user accounts. It is the first easy and secure user management and authentication service for developers.
> 
> Built for developers, it offers an easy API, open source SDKs, web-based administration console, and an active community. All of this for a flexible cloud service that can manage millions of users with a scalable pricing model that is ideal for projects of any size.
> 
> By offloading user management and authentication to Stormpath, developers can bring new applications to market faster, reduce development and operations costs, and protect their users with best-in-class security.

**Comment by omgitstom** [comment]
Sounds good!

**Comment by nbarbettini** [comment]
- [x] What you can do with Stormpath: "This means that we can operate in almost any software environment." This sounds awkward - perhaps "This means you can use Stormpath from any software environment"? **Done -JS**
- [x] The Stormpath Data Model: "Each Stormpath resource has a unique href **link** associated with it" Link is redundant, "unique `href` associated" is more correct. **Agreed. Fixed.**
