### ISSUE TITLE
Update Headers in two examples on REST Quickstart

### ISSUE THREAD

**Issue by brentstormpath** [stormpath/stormpath-documentation#40]
## Feedback from a Stormpath user:

You might also be interested to know that on the Quick Start page two (GET) request are shown having a 'content-type' header where I would expect an ‘accept’ header.

Ex: 
curl --request GET \ 
--user $API_KEY_ID:$API_KEY_SECRET \ 
--header 'content-type: application/json' \ 
--url "https://api.stormpath.com/v1/tenants/current" 

and

curl --request GET \ 
--user $API_KEY_ID:$API_KEY_SECRET \ 
--header 'content-type: application/json' \ 
--url "https://api.stormpath.com/v1/tenants/yOuRTeNANtid/applications?name=My%20Application" 
I’ve verified this and indeed replacing the header with ‘Accept’ does work as expected, also omitting the header does work.

**Comment by jakubvul** [comment]
Fair point!
