### ISSUE TITLE
SAML ADFS info

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#45]
We should have information about how to configure SAML with ADFS.

**Comment by gbodet-fa** [comment]
Hi,
Any update on this topic? We need to setup external SSO with a customer ADFS, based on the SAML metadata.xml file provided by ADFS... Any clue would be highly appreciated.
Regards

**Comment by jakubvul** [comment]
Hi @gbodet-fa, we're still in the development/testing phase of this, but I'll be sure to update this issue as soon as I am able to start work on documentation!

**Comment by jakubvul** [comment]
Hello again @gbodet-fa, I'm happy to report that we now have configuration instructions for manually setting up SSO via ADFS: https://docs.stormpath.com/rest/product-guide/latest/auth_n.html#adfs
