### ISSUE TITLE
The "Sorting" section has an irrelevant example

### ISSUE THREAD

**Issue by rbhojan** [stormpath/stormpath-documentation#46]
The Sorting section the REST Guide, has in irrelevant example, i.e it has a sample request for pagination (limit, offset) instead of sorting (orderBy). Please check the attachment for screenshot.
<img width="835" alt="screen shot 2016-02-02 at 1 21 13 pm" src="https://cloud.githubusercontent.com/assets/6137543/12764788/6fecbe24-c9b0-11e5-810c-4db9ab3c3755.png">

**Comment by jakubvul** [comment]
Nice catch!

**Comment by jakubvul** [comment]
Fixed: http://docs.stormpath.com/rest/product-guide/latest/reference.html#sorting
