### ISSUE TITLE
Setup Section Feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#5]

**Comment by nbarbettini** [comment]
- [x] Sign-up for Stormpath: "1. First, go to" looks redundant to me, like "PIN number" :smile: 
- [x] Sign-up for Stormpath: "From this screen, re-enter your password and click “Log In” to enter the Admin Console. From here" - sounds like too many "froms" when I read it in my head.
- [x] Sign-up for Stormpath: "From here **you** will be able to perform all of the administrative functions required for your Stormpath Account. **Let’s** start by creating an API key." - this felt like a weird shift from second to third grammatical person to me, but I might be wrong.
