### ISSUE TITLE
IdP Initiated SAML via REST

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#54]
https://stormpath.atlassian.net/wiki/display/AM/SAML+Identity+Provider+Initiation

**Comment by jakubvul** [comment]
### Changes

#### Reference Chapter

SP resource has a new defaultRelayStates endpoint. You hit it with a POST and you get back the JWT that you need to configure into the IdP as your relay state.

```
HTTP/1.1 POST
https://api.stormpath.com/v1/samlServiceProviders/2JkimYM3WjjYzDtuTx8y5x/defaultRelayStates

{
    "callbackUri": "https://org1.myapp.com", //optional
    "organization": {
        "nameKey": "org1", //optional
    }
    "state": "" //optional
    "apiKey" : {
        "href": "" //optional if invoked from api
    }
}
```

Response:

```
HTTP/1.1 200 OK

{
    "defaultRelayState": "{GENERATED JWT}"
}
```

#### AuthN Chapter

**5.5 Authenticating Against a SAML Directory**

Pre-amble briefly explaining the difference between SP-init and IdP-init.

**5.5.1. Stormpath as a Service Provider**

High-level new info about IdP-init goes here.

*_5.5.2. Configuring SAML *_

_Requires Admin Console updates for full instructions._

**5.5.3. Configuring SAML Via REST**

Add information about defaultRelayStates endpoint and POSTing to it, not sure what else...

**5.5.4. The Stormpath SAML Flow**

Split into two sections: IdP-init and SP-init
Include IdP init step-by-step description here along with new flow diagram
