### ISSUE TITLE
Multi-part Emails

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#61]
Presumably these two sections should be updated now that we support multi-part emails:

https://docs.stormpath.com/rest/product-guide/latest/reference.html#email-templates

https://docs.stormpath.com/rest/product-guide/latest/accnt_mgmt.html#customizing-email-templates

Existing information can be found here: https://stormpath.atlassian.net/browse/AM-2919 and here: https://stormpath.atlassian.net/wiki/display/AM/Directory+Related+REST+API+for+UI

**Comment by lhazlewood** [comment]
Yep! Good catch.
