### ISSUE TITLE
Create scaffolding for multi-language Product Guide

### ISSUE THREAD

**Issue by jakubvul** [stormpath/stormpath-documentation#71]
In order to create the scaffold that the evangelists will use to create the language-specific Product Guides, I need to go through the existing content and create the `only:: <language>` sections and code folders. Perhaps even more importantly this requires me to read through the existing content and remove anything that is specific to REST. 

Once this task is complete I will pass on this scaffolded Product Guide to the individual evangelists so that they can add their language-specific content. 
- [x] Quickstart
- [x] Account Management
- [x] Authentication
- [x] Authorization
- [x] Multi-Tenancy
- [x] ID Site

**Comment by lhazlewood** [comment]
This is awesome, Awesome, _AWESOME_.  Thank you!

**Comment by jakubvul** [comment]
Account Management scaffolding is complete, dummy files are in the appropriate sub-directories.

**Comment by nbarbettini** [comment]
Suggestion: you could add checkboxes to the top post that represent each section, then check 'em off as you scaffold. Then you'd get a sweet progress bar on this issue. :smile:

**Comment by jakubvul** [comment]
@nbarbettini I did it! 

...but I don't see a progress bar. :(

**Comment by nbarbettini** [comment]
It shows up on the Issues overview screen:

![screen shot 2016-03-21 at 11 45 51 am](https://cloud.githubusercontent.com/assets/7525482/13930074/8b78fda4-ef5a-11e5-88ff-3932b149c1a2.png)

**Comment by nbarbettini** [comment]
Nice! 🎉
