### ISSUE TITLE
What role do organizations play in multi-tenancy

### ISSUE THREAD

**Issue by DonDebonair** [stormpath/stormpath-documentation#75]
I've read the section in the user guide about multi-tenancy, and I'm interested in setting up multi-tenancy using the [group-as-tenant approach](https://docs.stormpath.com/rest/product-guide/latest/multitenancy.html#strategy-2-tenants-as-groups). The thing I'm trying to understand, is why you would want to have an extra level of indirection by using _organizations_.

The user guide states:

> You can still control access to the Application by enabling or disabling the accountStoreMappings between the Organizations and the Application resource.

Couldn't you control access to the Application for a tenant, by having accountStoreMappings directly between Application and (tenant-)groups? You could just remove an accountStoreMapping between a (tenant-)group and the Application, if you want to deny every user of that tenant access. Am I missing something here?

**Comment by jakubvul** [comment]
Hey @DandyDev, you're absolutely right, you _can_ totally skip Organizations if you want and do exactly what you've described. Previously, the Group-per-Tenant approach was the one we recommended, and it still absolutely works. There are a few convenience features of Organizations that are worth highlighting:
1. Organization's have a DNS-compliant unique `nameKey`. This allows you to straightforwardly create login subdomains along the lines of `nameKey.yourapplication.com`. More importantly, you can pass the Organization's `nameKey` in your [Login Attempt](https://docs.stormpath.com/rest/product-guide/latest/reference.html#ref-loginattempts) without having to bother with a Group href. 
2. In more complex user models (multiple Groups/Directories per tenant, or Group-per-tenant as well as Role Groups, etc), the Organization resource gives you a single gateway between the Application and the Account Stores. This helps with controlling access, but also querying. 

They really are a convenience feature, and if you don't think they're required for your implementation, then you can absolutely skip them!

I hope this answers your question, but if you have any follow-up, shoot an email to support@stormpath.com and we'll help you from there.

**Comment by DonDebonair** [comment]
Thanks for the comprehensive answer!
