### ISSUE TITLE
Authentication Feedback

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#8]
- [x] 5 I feel like this section needs an intro. Authentication is the act of proving someone (or something) is actually who they say they are. When an account is authenticated, there is a high degree of certainty that the account identity is legitimate.  Stormpath gives you the ability to authenticate in different ways based on your application requirements...
- [x] 5a  How Login Attempts Work might read easier if it is right before Account Store Mappings.  My thoughts here is we explain how it works after we show them how to log in, then dive into managing account store mappings.
- [x] 5a An introduction section might work well here.  One of the most common ways of authentication is to ask for the account's credentials.  When you create an account in Stormpath, it is require that the account provides a username or email and a password.  These credentials can be provided to authenticate an account with password authentication.  Stormpath can be configured to support different password strength requirements for the accounts... 
- [x] 5c this section has a different tone then the rest of the guide.  I guess we switched from something Les wrote to something Randall wrote. **I don't think this has actually been written down anywhere. What happened here is that I spoke to Randall about Social Auth and took notes, then used those to write the section** :smile: 
- [x] 5c If Stormpath is unable to retrieve the user's first and last name, it will populate those attributes with a default value.  We should just tell them what the default value is
- [x] 5c I think this might be missing from the ToC, but this section should talk about authenticating against LDAP / AD directories.

**Comment by nbarbettini** [comment]
- [x] Authenticating an Account: "(more on these [below])" - missing link
- [x] Authenticating an Account: "Now the reason why this succeeds" - would read easier as simply "The reason this succeeds..."
- [x] Account Store Mappings: "by manipulating an Application’s AccountStoreMapping resources." should be "an Application's `accountStoreMapping` resources"? **In general, I'm not putting the name of resources into literal blocks. I prefer "Organization resource" to "`Organization` resource" and so on. -JS**
- [x] +1 to Tom's suggestion of switching up the order of How Login Attempts Work. Additionally, How to Retrieve Additional Account Data on Authentication could come before How Login Attempts Work - currently, it feels like it's low-level (showing you how to send a login requests), then goes high-level (the overall view of how login attempts work in abstract), then low-level again (how to expand the result).
- [x] Introduction to Token-Based Authentication: "This **help** you as a developer..."
- [x] Configuring Token-Based Authentication: POST request code block first `{` is indented incorrectly
- [x] Validating an Access Token: different colors on the table might make it easier to grok visually. **I believe this would require a modification to the global CSS styling in the Stormpath Sphinx Theme -JS**
- [x] Refreshing Access Tokens: "without re-inputting their credentials" - I think "re-entering" is more common phrasing
- [x] How Social Authentication Works: point 4: missing period at end of sentence
- [x] Step 1: Create a Social Directory for Google: too much indent on first line
- [x] Step 3: Access an Account with Google Tokens: both code blocks have too much indent on first line
- [x] Step 1: Create a Social Directory for Facebook: too much indent on first line
- [x] Step 1: Create a Social Directory for GitHub: too much indent on first line
- [x] The GitHub guide is missing a step. ou also have to exchange the Github temporary code for an access token before sending it to Stormpath. pinging @omgitstom - can show you a code demonstration **This is a defect which will soon be fixed -JS**
- [x] Step 1: Create a Social Directory for LinkedIn: too much indent on first line
- [x] Step 1: Create a Social Directory for LinkedIn: `providerId` is `github` :wink:
