### ISSUE TITLE
[Account Management] - Resend Verification Email

### ISSUE THREAD

**Issue by bretterer** [stormpath/stormpath-documentation#88]
Going through and adding in PHP Docs, I found a little bit of a hole.  Going through the whole setup, we create a directory, we add an account to that directory, add a group to the directory, link the account and group.  This is all working just fine.  The issue comes in when we talk about doing the resending of the verification email.  We have to talk to the application for this.

During all of this, we never map the directory to the application, causing us to not be able to send a password reset email for the account we have been working with through the whole docs page.

**Comment by jakubvul** [comment]
That's a good point Brian! I left the ASM creation to the Authentication chapter, but that definitely needs to be a step. I'll add in a quick section ASAP.

**Comment by jakubvul** [comment]
Fixed here: https://github.com/stormpath/stormpath-documentation/commit/883d36e87e234ad12e2158a5aa1ba84cf09eceeb
