### ISSUE TITLE
Error in Group query syntax

### ISSUE THREAD

**Issue by nbarbettini** [stormpath/stormpath-documentation#92]
In [Account Management](https://github.com/stormpath/stormpath-documentation/blob/master/source/accnt_mgmt.rst), section 4.1.2. Groups:

> A geographical region can, for example, be represented as `"North America/US/US East"` in the Group's `description` field, allowing for queries to be made using simple pattern-matching queries. So to find all Groups in the US, you'd make the following HTTP GET:
> 
> ```
> https://api.stormpath.com/v1/directories/$DIR_ID/groups?description=US*
> ```
> 
> Or, to find all Groups in the US East region only, you would GET:
> 
> ```
> https://api.stormpath.com/v1/directories/$DIR_ID/groups?description=US%20East*
> ```

These queries wouldn't work, because the `description=US*` syntax means "anything starting with "US". (see [Matching Logic](https://docs.stormpath.com/rest/product-guide/latest/reference.html#id2))

Maybe this should be `description=*/US*` and `description=*/US East*`?

**Comment by jakubvul** [comment]
An excellent point @nbarbettini.

**Comment by jakubvul** [comment]
I've updated it to say:

`GET /v1/directories/$DIRECTORY_ID/groups?description=*/US*`

and

`GET /v1/directories/$DIR_ID/groups?description=*/US%20East*`

**Comment by jakubvul** [comment]
Fixed: a2144a8bdaf692bf1bb7c1e1554167797d59f180
