### ISSUE TITLE
First curl command in Quickstart guide doesn't return anything

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-documentation#93]
The first command in in the [Quickstart guide](https://docs.stormpath.com/rest/product-guide/latest/quickstart.html) doesn't return anything.

```
curl --request GET \
 --user $SP_API_KEY_ID:$SP_API_KEY_SECRET \
 --header 'content-type: application/json' \
 --url "https://api.stormpath.com/v1/tenants/current”
```

It says it returns a 302 and location header, but it's not visible when using the command above. Adding `-v` returns all headers and you can see the Location header. Appending `-L` to the command returns JSON.

**Comment by lhazlewood** [comment]
@mraible was this comment truncated? `-v` isn't necessary if you use `-L`...

**Comment by mraible** [comment]
@lhazlewood Yep, I fixed it. `-L` returns JSON because it follows the location header. However, the documentation states that you should see the header and use it in the next command.

> Make note of the Location header. This is the location of your Tenant in Stormpath, which you will need in the next step.

**Comment by lhazlewood** [comment]
Ah, yeah, that's true if you're looking at the raw rest response, which isn't necessary when using cURL

**Comment by jakubvul** [comment]
Thanks @mraible. I've fixed this, so the command is now:

```
curl --request GET \
      --verbose \
      --user $SP_API_KEY_ID:$SP_API_KEY_SECRET \
      --header 'content-type: application/json' \
      --url "https://api.stormpath.com/v1/tenants/current"
```
