### ISSUE TITLE
The REST Quickstart guide uses two different variables for tentant id

### ISSUE THREAD

**Issue by mraible** [stormpath/stormpath-documentation#94]
In https://docs.stormpath.com/rest/product-guide/latest/quickstart.html:

> From here, using the location of the Tenant, you can get your Application by performing a search for the Application by name, with $TENANT_HREF replaced with the href of your Tenant from the previous cURL:

```
curl --request GET \
  --user $SP_API_KEY_ID:$SP_API_KEY_SECRET \
  --header 'content-type: application/json' \
  --url "https://api.stormpath.com/v1/tenants/yOuRTeNANtid/applications?name=My%20Application"
```

Notice that paragraph talks about using a `$TENANT_HREF`, but then uses `yOuRTeNANtid` in the curl command. It seems this would be better if the same variable was used in both places.

**Comment by jakubswiatczak** [comment]
Thanks @mraible. I've fixed this, so the command is now:

```
curl --request GET \
      --verbose \
      --user $SP_API_KEY_ID:$SP_API_KEY_SECRET \
      --header 'content-type: application/json' \
      --url "https://api.stormpath.com/v1/tenants/current"
```

**Comment by jakubvul** [comment]
Good catch @mraible 

The URL now looks like this:

```
  .. code-block:: bash

    curl --request GET \
      --user $SP_API_KEY_ID:$SP_API_KEY_SECRET \
      --header 'content-type: application/json' \
      --url "https://api.stormpath.com/v1/tenants/$TENANT_ID/applications?name=My%20Application"
```

I've also updated the text above the command to clarify what it is that you're using:

> Make note of the `Location` header. This is the location of your Tenant in Stormpath, with the Tenant's unique ID at the end.
> 
> From here, using your Tenant ID, you can get your Application by performing a search for the Application by name, with $TENANT_ID replaced with your Tenant's ID from the previous cURL:

**Comment by mraible** [comment]
:+1:
