### ISSUE TITLE
Error Codes & Messages

### ISSUE THREAD

**Issue by omgitstom** [stormpath/stormpath-documentation#99]
Need to update documentation to include the error messages:

https://docs.stormpath.com/errors/

**Comment by jakubvul** [comment]
https://github.com/stormpath/stormpath-documentation/tree/develop

**Comment by jakubvul** [comment]
This should be a single page that will have all of the error information. 

Since the old documentation links to individual error pages, with one error per page, we will have to create redirects and the platform will have to return new links.

**Comment by jakubvul** [comment]
https://docs.stormpath.com/rest/product-guide/latest/errors.html
